from pydantic import BaseModel, Field
from typing import Optional
from datetime import date, datetime


class PatientRegistrationCreate(BaseModel):
    name: str
    age: Optional[int] = None
    gender: Optional[str] = None
    phone: Optional[str] = None
    address: Optional[str] = None
    guardian_name: Optional[str] = None
    photo_base64: Optional[str] = None
    # UHID is generated by backend after first save


class PatientRegistrationResponse(BaseModel):
    id: str
    uhid: str
    name: str
    age: Optional[int] = None
    gender: Optional[str] = None
    phone: Optional[str] = None
    address: Optional[str] = None
    guardian_name: Optional[str] = None
    photo_base64: Optional[str] = None
    created_at: Optional[datetime] = None


class OPDRegistrationCreate(BaseModel):
    uhid: str
    patient_name: Optional[str] = None
    department: Optional[str] = None
    doctor_id: Optional[str] = None
    visit_type: Optional[str] = "OPD"
    notes: Optional[str] = None


class IPDRegistrationCreate(BaseModel):
    uhid: str
    patient_name: Optional[str] = None
    ward: Optional[str] = None
    bed_number: Optional[str] = None
    admission_reason: Optional[str] = None
    admitted_by: Optional[str] = None
    notes: Optional[str] = None


class DoctorRegistrationCreate(BaseModel):
    name: str
    specialization: Optional[str] = None
    qualification: Optional[str] = None
    phone: Optional[str] = None
    email: Optional[str] = None
    department: Optional[str] = None


class StaffRegistrationCreate(BaseModel):
    name: str
    role: Optional[str] = None
    department: Optional[str] = None
    phone: Optional[str] = None
    email: Optional[str] = None


class AppointmentCreate(BaseModel):
    uhid: str
    patient_name: Optional[str] = None
    doctor_id: Optional[str] = None
    appointment_date: str
    appointment_time: Optional[str] = None
    type: Optional[str] = None  # therapy, opd, etc.
    notes: Optional[str] = None
