// Patient Registration – saves to backend; UHID is generated by backend after first save.
import React, { useState, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../../api/service";
import "./RegistrationForm.css";

function CollapsibleSection({ title, defaultOpen, children }) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div className="bahmni-section">
      <button type="button" className="bahmni-section-header" onClick={() => setOpen(!open)} aria-expanded={open}>
        <span>{title}</span>
        <span className="bahmni-section-icon">{open ? "▼" : "▶"}</span>
      </button>
      {open && <div className="bahmni-section-body">{children}</div>}
    </div>
  );
}

function PatientRegistration() {
  const navigate = useNavigate();
  const [submitting, setSubmitting] = useState(false);
  const [uhid, setUhid] = useState(""); // Set by backend after first save
  const [form, setForm] = useState({
    patientName: "",
    phone: "",
    age: "",
    dateOfBirth: "",
    estimatedAge: false,
    gender: "",
    houseNoStreet: "",
    village: "",
    district: "",
    state: "",
    pincode: "",
    bloodGroup: "",
    education: "",
    occupation: "",
    fatherHusbandName: "",
    identificationMark: "",
    smokingHistory: false,
    familyIncome: "",
    rationCardType: "",
    urbanRural: false,
    distanceFromCenter: "",
    relationshipType: "",
    relatedPersonNameOrId: "",
    relationshipValidTill: "",
    dateOfDeath: "",
    causeOfDeath: "",
    photo_base64: "", // Store photo as base64
  });

  const handlePhotoChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setForm((prev) => ({ ...prev, photo_base64: reader.result }));
      };
      reader.readAsDataURL(file);
    }
  };

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setForm((prev) => ({ ...prev, [name]: type === "checkbox" ? checked : value }));
  };

  const registrationDate = useMemo(() => new Date().toLocaleDateString("en-IN", { dateStyle: "long" }), []);

  const handleSave = async (e) => {
    e.preventDefault();
    setSubmitting(true);
    try {
      const res = await api.createPatient({ ...form, registrationDate });
      setUhid(res.uhid || "");
      alert(`Patient saved successfully. UHID: ${res.uhid}. Use this UHID for OPD, IPD, and appointments.`);
    } catch (err) {
      alert(err.message || "Failed to save patient.");
    } finally {
      setSubmitting(false);
    }
  };



  const handlePrintRegistrationCard = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
      <html><head><title>Registration Card - ${form.patientName}</title>
      <style>
        body { font-family: sans-serif; padding: 20px; }
        .card { width: 450px; border: 2px solid #2f6f6c; border-radius: 12px; padding: 15px; position: relative; overflow: hidden; }
        .header { display: flex; align-items: center; border-bottom: 2px solid #2f6f6c; padding-bottom: 10px; margin-bottom: 15px; }
        .logo { width: 50px; height: 50px; margin-right: 15px; }
        .hospital-info h1 { font-size: 18px; color: #2f6f6c; margin: 0; }
        .hospital-info p { font-size: 10px; margin: 2px 0; color: #666; }
        .card-body { display: flex; gap: 20px; }
        .photo-box { width: 100px; height: 120px; border: 1px solid #ccc; display: flex; align-items: center; justify-content: center; background: #f9f9f9; overflow: hidden; }
        .photo-box img { width: 100%; height: 100%; object-fit: cover; }
        .details { flex: 1; }
        .details p { margin: 8px 0; font-size: 14px; }
        .label { font-weight: bold; color: #555; width: 60px; display: inline-block; }
        .uhid { font-size: 16px; font-weight: 800; color: #2f6f6c; border-top: 1px dashed #ccc; padding-top: 8px; margin-top: 10px; }
        .footer { font-size: 8px; text-align: center; margin-top: 15px; color: #999; border-top: 1px solid #eee; padding-top: 5px; }
      </style></head>
      <body>
        <div class="card">
          <div class="header">
            <img src="/swastiklogo.png" class="logo" onerror="this.src='https://via.placeholder.com/50'"/>
            <div class="hospital-info">
              <h1>SWASTIK HOSPITAL</h1>
              <p>Psychiatric & Rehabilitation Centre</p>
              <p>Near City Plaza, Main Road, Kolhapur</p>
            </div>
          </div>
          <div class="card-body">
            <div class="photo-box">
              ${form.photo_base64 ? `<img src="${form.photo_base64}" />` : "<span>PHOTO</span>"}
            </div>
            <div class="details">
              <p><span class="label">Name:</span> <strong>${form.patientName || "—"}</strong></p>
              <p><span class="label">Age/Sex:</span> ${form.age || "—"} / ${form.gender || "—"}</p>
              <p><span class="label">Phone:</span> ${form.phone || "—"}</p>
              <div class="uhid">UHID: ${uhid || "NOT SAVED"}</div>
            </div>
          </div>
          <div class="footer">
            ORELSE Private Limited | Registration Date: ${registrationDate}
          </div>
        </div>
        <script>window.onload = function() { window.print(); window.close(); }</script>
      </body></html>
    `);
    printWindow.document.close();
  };

  const handlePrintPatientSummary = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
      <html><head><title>Patient Summary - ${form.patientName}</title>
      <style>
        body { font-family: sans-serif; padding: 40px; line-height: 1.6; }
        .header { display: flex; justify-content: space-between; border-bottom: 3px solid #1e40af; padding-bottom: 15px; margin-bottom: 25px; }
        .hospital-name { font-size: 28px; font-weight: bold; color: #1e40af; }
        .patient-info { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; background: #f8fafc; padding: 20px; border: 1px solid #e2e8f0; margin-bottom: 25px; }
        h3 { color: #1e40af; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; margin-top: 30px; }
        .label { font-weight: bold; color: #334155; min-width: 140px; display: inline-block; }
        .footer { margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; font-size: 12px; color: #64748b; }
      </style></head>
      <body>
        <div class="header">
          <div>
            <div class="hospital-name">SWASTIK HOSPITAL</div>
            <p>Integrated Digital Healthcare Management</p>
          </div>
          <div style="text-align: right">
            <h2 style="color: #1e40af; margin: 0;">PATIENT REGISTRATION SUMMARY</h2>
            <p>UHID: ${uhid || "N/A"}</p>
          </div>
        </div>
        <div class="patient-info">
          <div><span class="label">Full Name:</span> ${form.patientName || "—"}</div>
          <div><span class="label">UHID / ID:</span> ${uhid || "—"}</div>
          <div><span class="label">Age / Gender:</span> ${form.age || "—"} / ${form.gender || "—"}</div>
          <div><span class="label">Phone:</span> ${form.phone || "—"}</div>
        </div>
        <h3>Demographic Details</h3>
        <table>
          <tr><td class="label">Date of Birth:</td><td>${form.dateOfBirth || "—"}</td></tr>
          <tr><td class="label">Address:</td><td>${[form.houseNoStreet, form.village, form.district, form.state, form.pincode].filter(Boolean).join(", ") || "—"}</td></tr>
          <tr><td class="label">Blood Group:</td><td>${form.bloodGroup || "—"}</td></tr>
          <tr><td class="label">Education:</td><td>${form.education || "—"}</td></tr>
          <tr><td class="label">Occupation:</td><td>${form.occupation || "—"}</td></tr>
          <tr><td class="label">Father/Husband Name:</td><td>${form.fatherHusbandName || "—"}</td></tr>
        </table>
        <h3>Social & Medical Info</h3>
        <table>
          <tr><td class="label">Family Income:</td><td>${form.familyIncome || "—"}</td></tr>
          <tr><td class="label">Ration Card:</td><td>${form.rationCardType || "—"}</td></tr>
          <tr><td class="label">Smoking History:</td><td>${form.smokingHistory ? "Yes" : "No"}</td></tr>
          <tr><td class="label">Identification Mark:</td><td>${form.identificationMark || "—"}</td></tr>
        </table>
        <div class="footer">
          © ${new Date().getFullYear()} Swastik Hospital. All rights reserved. | Registration Date: ${registrationDate}
        </div>
        <script>window.onload = function() { window.print(); window.close(); }</script>
      </body></html>
    `);
    printWindow.document.close();
  };

  const handlePrint = (option) => {
    if (option === "registration-card") handlePrintRegistrationCard();
    if (option === "patient-summary") handlePrintPatientSummary();
  };

  return (
    <div className="registration-page-wrapper">
      <div className="registration-form-page">
        <div className="registration-form-header-row">
          <div>
            <h2>Patient Registration</h2>
            <p className="registration-form-subtitle">Register new patients and generate UHID</p>
          </div>
          <div className="print-actions no-print">
            <button type="button" className="print-btn" onClick={() => handlePrint("registration-card")}>
              Print Registration Card
            </button>
            <button type="button" className="print-btn" onClick={() => handlePrint("patient-summary")}>
              Print Patient Summary
            </button>
          </div>
        </div>

        <div className="patient-summary-print print-only-content">
          <h3 className="print-hospital-name">Swastik Hospital</h3>
          <p><strong>Patient Identifier (UHID):</strong> {uhid}</p>
          <p><strong>Patient Name:</strong> {form.patientName || "—"}</p>
          <p><strong>Age / Gender:</strong> {form.age || "—"} / {form.gender || "—"}</p>
          <p><strong>Address:</strong> {[form.houseNoStreet, form.village, form.district, form.state, form.pincode].filter(Boolean).join(", ") || "—"}</p>
          <p><strong>Registration Date:</strong> {registrationDate}</p>
        </div>

        <form onSubmit={handleSave} className="registration-form-fields bahmni-form">
          <CollapsibleSection title="Demographics" defaultOpen>
            <div className="form-row full-width">
              <label>Patient Identifier (UHID)</label>
              <input type="text" value={uhid || "— Generated after first save —"} readOnly className="readonly-uhid" />
            </div>
            <div className="form-row">
              <label>Patient Name *</label>
              <input name="patientName" value={form.patientName} onChange={handleChange} placeholder="Full name" required />
            </div>
            <div className="form-row">
              <label>Phone Number *</label>
              <input name="phone" type="tel" value={form.phone} onChange={handleChange} placeholder="Phone" required />
            </div>
            <div className="form-row">
              <label>Age / Date of Birth</label>
              <div className="age-dob-row">
                <input name="age" value={form.age} onChange={handleChange} placeholder="Age" />
                <input name="dateOfBirth" type="date" value={form.dateOfBirth} onChange={handleChange} />
              </div>
            </div>
            <div className="form-row">
              <label className="checkbox-label">
                <input type="checkbox" name="estimatedAge" checked={form.estimatedAge} onChange={handleChange} />
                Estimated Age
              </label>
            </div>
            <div className="form-row">
              <label>Gender *</label>
              <select name="gender" value={form.gender} onChange={handleChange} required>
                <option value="">Select</option>
                <option value="Male">Male</option>
                <option value="Female">Female</option>
                <option value="Other">Other</option>
              </select>
            </div>
            <div className="form-row">
              <label>Patient Photo</label>
              <input type="file" accept="image/*" onChange={handlePhotoChange} />
              {form.photo_base64 && (
                <div className="photo-preview">
                  <img src={form.photo_base64} alt="Preview" style={{ width: "60px", height: "60px", marginTop: "10px", borderRadius: "8px", objectFit: "cover" }} />
                </div>
              )}
            </div>
          </CollapsibleSection>

          <CollapsibleSection title="Address Information" defaultOpen>
            <div className="form-row full-width">
              <label>House No / Street</label>
              <input name="houseNoStreet" value={form.houseNoStreet} onChange={handleChange} placeholder="House no, street" />
            </div>
            <div className="form-row">
              <label>Village *</label>
              <input name="village" value={form.village} onChange={handleChange} placeholder="Village" required />
            </div>
            <div className="form-row">
              <label>District *</label>
              <input name="district" value={form.district} onChange={handleChange} placeholder="District" required />
            </div>
            <div className="form-row">
              <label>State *</label>
              <input name="state" value={form.state} onChange={handleChange} placeholder="State" required />
            </div>
            <div className="form-row">
              <label>Pincode *</label>
              <input name="pincode" value={form.pincode} onChange={handleChange} placeholder="Pincode" required />
            </div>
          </CollapsibleSection>

          <CollapsibleSection title="Other Information" defaultOpen>
            <div className="form-row">
              <label>Blood Group</label>
              <select name="bloodGroup" value={form.bloodGroup} onChange={handleChange}>
                <option value="">Select</option>
                <option value="A+">A+</option>
                <option value="A-">A-</option>
                <option value="B+">B+</option>
                <option value="B-">B-</option>
                <option value="O+">O+</option>
                <option value="O-">O-</option>
                <option value="AB+">AB+</option>
                <option value="AB-">AB-</option>
              </select>
            </div>
            <div className="form-row">
              <label>Education Details</label>
              <input name="education" value={form.education} onChange={handleChange} placeholder="Education" />
            </div>
            <div className="form-row">
              <label>Occupation</label>
              <input name="occupation" value={form.occupation} onChange={handleChange} placeholder="Occupation" />
            </div>
            <div className="form-row">
              <label>Father's / Husband's Name</label>
              <input name="fatherHusbandName" value={form.fatherHusbandName} onChange={handleChange} placeholder="Name" />
            </div>
            <div className="form-row full-width">
              <label>Identification Mark</label>
              <input name="identificationMark" value={form.identificationMark} onChange={handleChange} placeholder="Identification mark" />
            </div>
            <div className="form-row">
              <label className="checkbox-label">
                <input type="checkbox" name="smokingHistory" checked={form.smokingHistory} onChange={handleChange} />
                Smoking History
              </label>
            </div>
          </CollapsibleSection>

          <CollapsibleSection title="Additional Patient Information">
            <div className="form-row">
              <label>Family Income</label>
              <input name="familyIncome" value={form.familyIncome} onChange={handleChange} placeholder="Income" />
            </div>
            <div className="form-row">
              <label>Ration Card Type</label>
              <select name="rationCardType" value={form.rationCardType} onChange={handleChange}>
                <option value="">Select</option>
                <option value="APL">APL</option>
                <option value="BPL">BPL</option>
                <option value="AAY">AAY</option>
                <option value="None">None</option>
              </select>
            </div>
            <div className="form-row">
              <label className="checkbox-label">
                <input type="checkbox" name="urbanRural" checked={form.urbanRural} onChange={handleChange} />
                Urban / Rural
              </label>
            </div>
            <div className="form-row">
              <label>Distance from Center (km)</label>
              <input name="distanceFromCenter" type="text" value={form.distanceFromCenter} onChange={handleChange} placeholder="km" />
            </div>
          </CollapsibleSection>

          <CollapsibleSection title="Relationships">
            <div className="form-row">
              <label>Relationship Type</label>
              <select name="relationshipType" value={form.relationshipType} onChange={handleChange}>
                <option value="">Select</option>
                <option value="Doctor">Doctor</option>
                <option value="Parent">Parent</option>
                <option value="Sibling">Sibling</option>
              </select>
            </div>
            <div className="form-row">
              <label>Related Person Name or ID</label>
              <input name="relatedPersonNameOrId" value={form.relatedPersonNameOrId} onChange={handleChange} placeholder="Name or ID" />
            </div>
            <div className="form-row">
              <label>Relationship Valid Till</label>
              <input name="relationshipValidTill" type="date" value={form.relationshipValidTill} onChange={handleChange} />
            </div>
          </CollapsibleSection>

          <CollapsibleSection title="Death Information" defaultOpen={false}>
            <div className="form-row">
              <label>Date of Death</label>
              <input name="dateOfDeath" type="date" value={form.dateOfDeath} onChange={handleChange} />
            </div>
            <div className="form-row full-width">
              <label>Cause of Death</label>
              <input name="causeOfDeath" value={form.causeOfDeath} onChange={handleChange} placeholder="Cause" />
            </div>
          </CollapsibleSection>

          <div className="visit-actions no-print">
            <button type="submit" className="registration-submit-btn" disabled={submitting}>
              {submitting ? "Saving..." : "Save Patient"}
            </button>
            {/* <button type="button" className="visit-btn" onClick={() => startVisit("opd")} disabled={submitting}>Start OPD Visit</button>
            <button type="button" className="visit-btn" onClick={() => startVisit("ipd")} disabled={submitting}>Start IPD Visit</button>
            <button type="button" className="visit-btn" onClick={() => startVisit("emergency")} disabled={submitting}>Start Emergency Visit</button>
            <button type="button" className="visit-btn" onClick={() => startVisit("lab")} disabled={submitting}>Start Lab Visit</button>
            <button type="button" className="visit-btn" onClick={() => startVisit("pharmacy")} disabled={submitting}>Start Pharmacy Visit</button> */}
          </div>
        </form>
      </div>
    </div>
  );
}

export default PatientRegistration;
